# NumPy

In [4]:
import numpy as np
A = np.array([0,1,2,3])
A

array([0, 1, 2, 3])

In [2]:
A.shape = 2,2
A

array([[0, 1],
       [2, 3]])

In [5]:
A = np.array([ [0,1,2], [3,4,5] ])
A

array([[0, 1, 2],
       [3, 4, 5]])

In [6]:
A.ndim

2

In [7]:
A.shape

(2, 3)

In [8]:
dados = range(10)
B = np.array(dados)
B

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
B.ndim

1

In [10]:
B.shape

(10,)

In [11]:
B.shape = 5,2
B

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [12]:
B[1, 1] # lembrando que índices começam de 0.

3